---
# Tasks executed AFTER the symlink switch to current release

- name: Restart episciences-next service
  ansible.builtin.systemd:
    name: episciences-front-next
    state: restarted
    daemon_reload: true
  become: true

- name: Wait for service to be healthy
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: 3000
    delay: 3
    timeout: 60
