blank_issues_enabled: false
contact_links:
  - name: Documentation Episciences 📚
    url: https://doc.episciences.org/
    about: Consultez la documentation officielle de la plateforme Episciences
  - name: Foire Aux Questions (FAQ) ❓
    url: https://doc.episciences.org/faq/
    about: Réponses aux questions fréquentes des utilisateurs et équipes éditoriales
  - name: Support Utilisateurs & Éditeurs 💬
    url: https://www.episciences.org/contact-2/
    about: Besoin d'assistance ou question spécifique ? Contactez l'équipe Episciences
