---
# Preprod — non-sensitive deployment variables

ansistrano_deploy_via: git
ansistrano_git_repo: "https://github.com/CCSDForge/episciences-front-next.git"
ansistrano_git_branch: "develop"
ansistrano_deploy_to: "/var/www/episciences-front-next"
ansistrano_keep_releases: 3
ansistrano_shared_files:
  - .env
ansistrano_shared_paths:
  - external-assets
  - logs
ansistrano_before_symlink_tasks_file: "tasks/build.yml"
ansistrano_after_symlink_tasks_file: "tasks/restart.yml"
