declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_DOI_HOMEPAGE: string;
    NEXT_PUBLIC_ARXIV_HOMEPAGE: string;
    NEXT_PUBLIC_HAL_HOMEPAGE: string;
    NEXT_PUBLIC_ARCHIVE_SOFTWARE_HERITAGE_HOMEPAGE: string;
    NEXT_PUBLIC_ORCID_HOMEPAGE: string;
    NEXT_PUBLIC_TWITTER_HOMEPAGE: string;
    NEXT_PUBLIC_MATHJAX_HOMEPAGE: string;
    NEXT_PUBLIC_ZOTERO_HOMEPAGE: string;
    NEXT_PUBLIC_CREATIVE_COMMONS_HOMEPAGE: string;
  }
}
